// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiErrorCode } from "./ApiErrorCode";

export type ApiError = { error: ApiErrorCode, detail: string, };
