// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Look } from "./Look";

/**
 * Who you are. The recovery code is present only when it has just been
 * made, at sign-up or recovery, and is never shown again.
 */
export type ApiMe = { id: number, name: string, look: Look, recoveryCode?: string, };
