// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pose } from "./Pose";
import type { Tile } from "./Tile";
import type { Walk } from "./Walk";

export type CatView = { id: string, name: string, coat: string, at: Tile, pose: Pose, walk: Walk | null, heldBy: number | null, };
