// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Emote } from "./Emote";
import type { Tile } from "./Tile";

/**
 * What a client asks for. The server decides what happens (AGENTS.md).
 */
export type ClientMsg = { "type": "walkTo", tile: Tile, } | { "type": "say", text: string, to: number | null, } | { "type": "pet", cat: string, } | { "type": "call", cat: string, } | { "type": "grab", id: number, } | { "type": "take", kind: string, } | { "type": "place", to: Tile, } | { "type": "putBack", } | { "type": "putAway", } | { "type": "sit", id: number, } | { "type": "leave", } | { "type": "presence", hidden: boolean, } | { "type": "here", } | { "type": "emote", emote: Emote, };
