// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A small gesture anyone inside can make (design.md, "People").
 */
export type Emote = "wave" | "laugh" | "heart" | "yawn";
