// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FurnitureView = { id: number, kind: string, x: number, y: number, w: number, h: number, movable: boolean, blocks: boolean, 
/**
 * Other pieces can stand on it, as on a rug.
 */
under: boolean, seats: boolean, 
/**
 * Knocked over by a cat, until someone stands it back up.
 */
toppled: boolean, };
