// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FurnitureView } from "./FurnitureView";

/**
 * A piece someone is carrying.
 */
export type HeldView = { by: number, piece: FurnitureView, };
