// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A kind of furniture the catalogue offers.
 */
export type KindView = { kind: string, w: number, h: number, blocks: boolean, under: boolean, seats: boolean, };
