// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Look } from "./Look";
import type { Place } from "./Place";
import type { Tile } from "./Tile";
import type { Walk } from "./Walk";

export type PersonView = { id: number, name: string, look: Look, place: Place, at: Tile, walk: Walk | null, };
