// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inside the café, or waiting at the window (ADR 0008).
 */
export type Place = "inside" | "window";
