// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pose = "idle" | "walk" | "nap" | "sit" | "hide" | "eat" | "groom" | "play" | "held";
