// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FurnitureView } from "./FurnitureView";
import type { Tile } from "./Tile";

/**
 * The floor plan: `tiles` holds one string per row (W wall, G window, D door,
 * C chalkboard, . floor).
 */
export type RoomView = { width: number, height: number, tiles: Array<string>, door: Tile, furniture: Array<FurnitureView>, };
