// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FurnitureView } from "./FurnitureView";
import type { KindView } from "./KindView";
import type { Tile } from "./Tile";

/**
 * The floor plan: `tiles` holds one string per row (W wall, G window, D door,
 * C chalkboard, . floor). `furniture` is what stands on the floor, not what
 * someone carries.
 */
export type RoomView = { width: number, height: number, tiles: Array<string>, door: Tile, 
/**
 * The door's walkway, which nothing may stand on.
 */
walkway: Array<Tile>, furniture: Array<FurnitureView>, catalogue: Array<KindView>, };
