// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Emote } from "./Emote";
import type { ErrorCode } from "./ErrorCode";
import type { PersonView } from "./PersonView";
import type { Place } from "./Place";
import type { Pose } from "./Pose";
import type { Reaction } from "./Reaction";
import type { Snapshot } from "./Snapshot";
import type { Tile } from "./Tile";
import type { TrustView } from "./TrustView";
import type { Walk } from "./Walk";

/**
 * What the server tells clients: a snapshot on joining, then events in order.
 */
export type ServerMsg = { "type": "welcome", you: number, build: string, now: number, cap: number, snapshot: Snapshot, } | { "type": "replaced", } | { "type": "personJoined", person: PersonView, } | { "type": "personLeft", id: number, } | { "type": "personPlaced", id: number, place: Place, at: Tile, walk: Walk | null, } | { "type": "personMoved", id: number, walk: Walk, } | { "type": "catMoved", cat: string, walk: Walk, } | { "type": "catPosed", cat: string, pose: Pose, at: Tile, } | { "type": "catReacted", cat: string, reaction: Reaction, } | { "type": "said", from: number, text: string, to: number | null, ttlMs: number, } | { "type": "yourTrust", trust: TrustView, } | { "type": "emoted", from: number, emote: Emote, } | { "type": "stillThere", secs: number, } | { "type": "nudgeOver", } | { "type": "furnitureMoved", id: number, at: Tile, by: number, } | { "type": "error", code: ErrorCode, detail: string, };
