// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Look } from "./Look";

export type SignUpRequest = { name: string, password: string, look: Look, };
