// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tile of the café floor; (0, 0) is the top-left, on the street wall.
 */
export type Tile = { x: number, y: number, };
