// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tile } from "./Tile";

/**
 * A treat someone put down, until a cat eats it.
 */
export type TreatView = { id: number, at: Tile, };
