// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustLevel } from "./TrustLevel";

/**
 * One cat's trust in you, 0 to 100, sent only to you.
 */
export type TrustView = { cat: string, value: number, level: TrustLevel, };
