// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tile } from "./Tile";

/**
 * A walk, sent once and animated by every client: the path's tiles in order,
 * when it started (server milliseconds) and tiles per second.
 */
export type Walk = { path: Array<Tile>, start: number, speed: number, };
